# Generated by Django 3.2.3 on 2021-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('title', models.CharField(max_length=50, verbose_name='Post title')),
                ('body', models.TextField()),
                ('published', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=50, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
