# Generated by Django 3.2.3 on 2021-05-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='post',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classification'),
            preserve_default=False,
        ),
    ]
