# Generated by Django 3.2.3 on 2021-05-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210522_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Rubric',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='classification',
            new_name='rubric',
        ),
    ]
